#!/bin/sh
# Compare demo output with known good demo output

srcdir=.
buildddir=.
if test "X$builddir" = "X" ; then
  builddir=.
fi
if test "X$srcdir" = "X" ; then
  srcdir=.
fi

rightfile=$srcdir/demo.right
outfile_full=$builddir/demo_full.out
outfile=$builddir/demo.out
$builddir/demo < /dev/null
exit $?
